### ISSUE TITLE
Top Navigation buttons don't work.

### ISSUE THREAD

**Issue by TheIntelloBox** [NiklasEi/2048-for-gamebox#3]
topNavigation: true

But in-game, if I click on the button "right" for example, tiles don't move to right.

**Comment by NiklasEi** [comment]
I introduced that issue in 3d954bb753a87eebaef75b1e30e0306770a1de86, when I fixed the 1.13 pre7 issue with #isSimilar.

**Comment by TheIntelloBox** [comment]
You fixed it ?

**Comment by NiklasEi** [comment]
Will do. Now that isSimilar is fine again, I can go back to the old system and it will work again.

**Comment by TheIntelloBox** [comment]
Nice. ;)
